---
- name: Create a new Jenkins user
  shell: |
    echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount("{{ user }}", "{{ password }}")' | java -jar /usr/local/bin/jenkins-cli.jar -auth {{ user }}:{{ jenkins_initial_admin_password }} -s {{ controller_url }} groovy =
  args:
    executable: /bin/bash
  register: create_user_output
  ignore_errors: true
  failed_when: false

- name: Display task output
  debug:
    var: create_user_output.stdout_lines