---
- name: Ensure Jenkins Agent Directory Exists
  ansible.builtin.file:
    path: /opt/jenkins
    state: directory

- name: Download Jenkins Agent JAR
  ansible.builtin.get_url:
    url: "{{ jenkins_controller_url }}/jnlpJars/agent.jar"
    dest: /opt/jenkins/agent.jar
    mode: "0755"

- name: Add Jenkins Agent to Systemd
  ansible.builtin.template:
    src: jenkins-agent.service.j2
    dest: /etc/systemd/system/jenkins-agent.service
  notify: Restart Jenkins Agent

- name: Start and Enable Jenkins Agent Service
  ansible.builtin.systemd:
    name: jenkins-agent
    state: started
    enabled: true
